<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTQKhsmr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTQKhsmr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTQKhsmr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTQKhsmr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTQKhsmr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TQKhsmr',
    'container.build_id' => '8d99557d',
    'container.build_time' => 1570798291,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTQKhsmr');
